session_config:
  session_id: dev
  use_gpu: True
  aggregator: fedavg
  aggregator_args: None
  client_selection: fedavg
  client_selection_args:
    client_fraction: 1
  termination_condition: max_rounds
  termination_condition_args:
    max_rounds: 10
  validation_round_interval: 1
  checkpoint_interval: 5
  generate_plots: False
  wait_for_clients:
    min_clients: 1
    max_wait_s: 3600
    poll_interval_s: 10

benchmark_config:
  skip_benchmark: True
  model_id: ResNet18
  model_dir: ../models/ResNet18
  model_class: ResNet18
  dataset: IMAGENET_NIID60_F16_12
  bench_minibatch_count: 500
  batch_size: 16
  learning_rate: 0.001
  timeout_duration_s: 120

server_training_config:
  model_dir: ../models/ResNet18
  global_model_validation_batch_size: 100

client_training_config:
  model_id: ResNet18
  model_class: ResNet18_Model
  epochs: 1
  dataset: IMAGENET_NIID60_F16_12
  batch_size: 16
  learning_rate: 0.001
  train_timeout_duration_s: 300
  loss_function: crossentropy
  loss_function_custom: True
  optimizer: adam
  optimizer_custom: True

model_config:
  use_custom_client_dataloader: True
  custom_client_loader_args: None
  
  use_custom_server_dataloader: True
  custom_server_loader_args: None

  use_custom_trainer: True
  custom_trainer_args: None

  use_custom_validator: True
  custom_validator_args: None

  model_args:
    num_classes: 60
    dropout_rate: 0.1
